export default [
  {
    id: 1,
    symbol: "USD",
    name: "United States",
    code: "&#x24",
    rate: 0,
    flag: "us",
  },
  {
    id: 2,
    symbol: "EUR",
    name: "European Union",
    code: "&#x",
    rate: 0,
    flag: "eu",
  },
  { id: 3, symbol: "JPY", name: "Japan", code: "&#xa5", rate: 0, flag: "jp" },
  {
    id: 4,
    symbol: "GBP",
    name: "United Kingdom",
    code: "&#xa3",
    rate: 0,
    flag: "gb",
  },
  {
    id: 5,
    symbol: "AUD",
    name: "Australia",
    code: "&#x24",
    rate: 0,
    flag: "au",
  },
  { id: 6, symbol: "CAD", name: "Canada", code: "&#x24", rate: 0, flag: "ca" },
  {
    id: 7,
    symbol: "CHF",
    name: "Switzerland",
    code: "&#x43,&#x48,&#x46",
    rate: 0,
    flag: "sw",
  },
  {
    id: 8,
    symbol: "CNY",
    name: "China",
    code: "&#xa5",
    rate: 0,
    flag: "cn",
  },
  {
    id: 9,
    symbol: "SEK",
    name: "Sweden",
    code: "&#x6b,&#x72",
    rate: 0,
    flag: "sw",
  },
  {
    id: 10,
    symbol: "NZD",
    name: "New Zealand",
    code: "&#x24",
    rate: 0,
    flag: "nz",
  },
];
