export default [
  {
    id: 1,
    symbol: "USD",
    name: "United States",
    code: "&#x24",
    rate: 0,
    flag: "us",
    locale: "en-US",
  },
  {
    id: 2,
    symbol: "EUR",
    name: "European Union",
    code: "&#x",
    rate: 0,
    flag: "eu",
    locale: "en-US",
  },
  {
    id: 3,
    symbol: "JPY",
    name: "Japan",
    code: "&#xa5",
    rate: 0,
    flag: "jp",
    locale: "ja-JP",
  },
  {
    id: 4,
    symbol: "GBP",
    name: "United Kingdom",
    code: "&#xa3",
    rate: 0,
    flag: "gb",
    locale: "en-GB",
  },
  {
    id: 5,
    symbol: "AUD",
    name: "Australia",
    code: "&#x24",
    rate: 0,
    flag: "au",
    locale: "en-AU",
  },
  {
    id: 11,
    symbol: "CRC",
    name: "Costa Rica",
    code: "&#x20A1;",
    rate: 0,
    flag: "cr",
    locale: "es-CR",
  },
  {
    id: 6,
    symbol: "CAD",
    name: "Canada",
    code: "&#x24",
    rate: 0,
    flag: "ca",
    locale: "en-CA",
  },
  {
    id: 7,
    symbol: "CHF",
    name: "Switzerland",
    code: "&#x43,&#x48,&#x46",
    rate: 0,
    flag: "ch",
    locale: "ch-FR",
  },
  {
    id: 8,
    symbol: "CNY",
    name: "China",
    code: "&#xa5",
    rate: 0,
    flag: "cn",
    locale: "zh-CN",
  },
  {
    id: 9,
    symbol: "SEK",
    name: "Sweden",
    code: "&#x6b,&#x72",
    rate: 0,
    flag: "se",
    locale: "us-SE",
  },
  {
    id: 10,
    symbol: "NZD",
    name: "New Zealand",
    code: "&#x24",
    rate: 0,
    flag: "nz",
    locale: "en-NZ",
  },
];
